name:          "WTF, HTML y CSS?"
url:           http://uncasually.github.io/wtf-html-y-css/
repo:          https://github.com/uncasually/wtf-html-y-css
twitter:       https://twitter.com/uncasually


markdown:      kramdown
permalink:     pretty
pygments:      true
