name:          "WTF, HTML e CSS?"
url:           http://aauri.github.io/wtf-html-css/
repo:          https://github.com/aauri/wtf-html-css
twitter:       https://twitter.com/mdo


markdown:      redcarpet
permalink:     pretty
pygments:      true
